### ISSUE TITLE
waved flag miss the semi-transparent borders and soft-light shade

### ISSUE THREAD

**Issue by anthrotype** [rsheeter/warp#20]
See https://github.com/googlefonts/noto-emoji/blob/main/waveflag.c#L316-L358

**Comment by anthrotype** [comment]
I put some `printf` in waveflag.c and figured that the following flags don't get added any border, seemingly because they are in part transparent (at least that's what I understood from the [`border_is_transparent` function](https://github.com/googlefonts/noto-emoji/blob/9a5261d871451f9b5183c93483cbd68ed916b1e9/waveflag.c#L155-L184)):

third_party/region-flags/png/CA-SK.png
third_party/region-flags/png/GF.png
third_party/region-flags/png/MQ.png
third_party/region-flags/png/NP.png
third_party/region-flags/png/PM.png
third_party/region-flags/png/US-CA.png
third_party/region-flags/png/US-MO.png
third_party/region-flags/png/US-NC.png
third_party/region-flags/png/US-OH.png
third_party/region-flags/png/US-TN.png

(the subdivision flags could probably be ingored as they don't get compiled into the noto-emoji font anyway)

So if we want to match exactly the bitmap we would have to avoid adding a border for these flags.

Now, some of these make sense, like Nepal flag which unlike the other rectangular ones and is made of two triangles. 
https://emojipedia.org/flag-nepal/

Others don't make sense to me, e.g. but why the flag of the French Guiana or Martinique or St. Pierre & Miquelon shold not have a border? They look pretty standard to me:
https://emojipedia.org/flag-french-guiana/
https://emojipedia.org/flag-martinique/
https://emojipedia.org/flag-st-pierre-miquelon/

**Comment by anthrotype** [comment]
Since we can't do this directly on the SVG files (because we don't have soft-light blending in SVG 1.1, as far as I know), I made an experimental utility to update the region flags from NotoColorEmoji COLRv1 table with a series of PaintComposites that blend the border and soft-light effects onto the existing color glyphs: 
https://github.com/googlefonts/noto-emoji/blob/colrv1-waved/colrv1_add_border_to_flags.py

Looks good enough to me.

(The first tab in screen recording is the original COLRv1, second tab is the updated one with border and soft-light shade, third tab is the CBDT bitmap font for reference)

https://user-images.githubusercontent.com/6939968/149566376-1436e9ae-1213-4e78-a235-4d6ffc2281f4.mov

**Comment by rsheeter** [comment]
LGTM! I like the obvious blurry/not-blurry COLR vs bitmap aspect of this demo :)

**Comment by rsheeter** [comment]
We should update https://github.com/googlefonts/noto-emoji/tree/svg_flags2?

**Comment by anthrotype** [comment]
> We should update https://github.com/googlefonts/noto-emoji/tree/svg_flags2?

For now, I cherry-picked https://github.com/googlefonts/noto-emoji/commit/24ccbd2377c08967cc2179fc417fe0cf3bf9f85e from `colrv1-waved` branch to `svg_flags2`, and updated color-fonts repo's submodule with it. So when building the test color-fonts at least waved flags will have correct aspect and margin (but still no border or soft light).

We need to think of a way to integrate this into the regular nanoemoji workflow. I'm thinking we can add a post-processing hook whereby a user provides a python script to be run after nanoemoji builds the color font.
